In [13]:
import pandas as pd

df = pd.read_csv('spam_dataset.csv')
df.head()

,Unnamed: 0,label,text,label_num
0,605,ham,Subject: enron methanol ; meter # : 988291\r\n...,0
1,2349,ham,"Subject: hpl nom for january 9 , 2001\r\n( see...",0
2,3624,ham,"Subject: neon retreat\r\nho ho ho , we ' re ar...",0
3,4685,spam,"Subject: photoshop , windows , office . cheap ...",1
4,2030,ham,Subject: re : indian springs\r\nthis deal is t...,0

In [14]:
df.describe()

        Unnamed: 0    label_num
count  5171.000000  5171.000000
mean   2585.000000     0.289886
std    1492.883452     0.453753
min       0.000000     0.000000
25%    1292.500000     0.000000
50%    2585.000000     0.000000
75%    3877.500000     1.000000
max    5170.000000     1.000000

In [15]:
df['text'][0]

"Subject: enron methanol ; meter # : 988291\r\nthis is a follow up to the note i gave you on monday , 4 / 3 / 00 { preliminary\r\nflow data provided by daren } .\r\nplease override pop ' s daily volume { presently zero } to reflect daily\r\nactivity you can obtain from gas control .\r\nthis change is needed asap for economics purposes ."

In [16]:
df.isna().sum()

Unnamed: 0    0
label         0
text          0
label_num     0
dtype: int64

In [17]:
df.dropna(inplace=True)

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

X= df['text']
Y= df['label']

vectorizer = CountVectorizer()
X= vectorizer.fit_transform(X)

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [20]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, Y_train)

LogisticRegression(max_iter=1000)

In [21]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

Y_pred=model.predict(X_test)
accuracy= accuracy_score(Y_test, Y_pred)
print('Accuracy:', accuracy)

Accuracy: 0.9806763285024155

In [22]:
import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

matrix = confusion_matrix(Y_test, Y_pred)
print("Confusion Matrix:")
print(matrix)

Confusion Matrix:
[[732  10]
 [ 10 283]]

In [23]:
report = classification_report(Y_test, Y_pred)
print('Classification Report:')
print(report)

Classification Report:
              precision    recall  f1-score   support

         ham       0.99      0.99      0.99       742
        spam       0.97      0.97      0.97       293

    accuracy                           0.98      1035
   macro avg       0.98      0.98      0.98      1035
weighted avg       0.98      0.98      0.98      1035

In [24]:
new_email = "Congratulations you have won one billion dollars for just breathing in..."
new_email_vectorized = vectorizer.transform([new_email])
prediction= model.predict(new_email_vectorized)
print("Prediction:", prediction)

Prediction: ['spam']